-- MySQL Script generated by MySQL Workbench
-- 05/12/16 13:41:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema worldgames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema worldgames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `worldgames` DEFAULT CHARACTER SET utf8 ;
USE `worldgames` ;

-- -----------------------------------------------------
-- Table `worldgames`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Shop` (
  `ID_Shop` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(45) NULL,
  PRIMARY KEY (`ID_Shop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Country` (
  `ID_Country` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(45) NULL,
  PRIMARY KEY (`ID_Country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Registered`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Registered` (
  `ID_Registered` INT NOT NULL AUTO_INCREMENT,
  `Username` CHAR(45) NULL,
  `Password` CHAR(45) NULL,
  `Email` CHAR(45) NULL,
  `BannedTime` FLOAT NULL,
  `BirthDate` DATE NULL,
  `PaypalAccount` CHAR(70) NULL,
  `AvatarURL` CHAR(70) NULL,
  `Shop_ID` INT NOT NULL,
  `Country_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Registered`, `Shop_ID`, `Country_ID`),
  INDEX `fk_Registered_Shop1_idx` (`Shop_ID` ASC),
  INDEX `fk_Registered_Country1_idx` (`Country_ID` ASC),
  CONSTRAINT `fk_Registered_Shop1`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `worldgames`.`Shop` (`ID_Shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered_Country1`
    FOREIGN KEY (`Country_ID`)
    REFERENCES `worldgames`.`Country` (`ID_Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Administrator` (
  `ID_Administrator` INT NOT NULL AUTO_INCREMENT,
  `Username` CHAR(50) NULL,
  `Password` CHAR(45) NULL,
  `Email` CHAR(45) NULL,
  `BannedTime` FLOAT NULL,
  `BirthDate` DATE NULL,
  `Shop_id_Shop` INT NOT NULL,
  PRIMARY KEY (`ID_Administrator`, `Shop_id_Shop`),
  INDEX `fk_Admistrador_Shop1_idx` (`Shop_id_Shop` ASC),
  CONSTRAINT `fk_Admistrador_Shop1`
    FOREIGN KEY (`Shop_id_Shop`)
    REFERENCES `worldgames`.`Shop` (`ID_Shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Professional` (
  `ID_Professional` INT NOT NULL AUTO_INCREMENT,
  `Username` CHAR(45) NULL,
  `Password` CHAR(45) NULL,
  `Email` CHAR(45) NULL,
  `BannedTime` FLOAT NULL,
  `BirthDate` DATE NULL,
  `Telephone` VARCHAR(45) NULL,
  `Shop_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Professional`, `Shop_ID`),
  INDEX `fk_Professional_Shop1_idx` (`Shop_ID` ASC),
  CONSTRAINT `fk_Professional_Shop1`
    FOREIGN KEY (`Shop_ID`)
    REFERENCES `worldgames`.`Shop` (`ID_Shop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Report` (
  `ID_Report` INT NOT NULL AUTO_INCREMENT,
  `Status` CHAR(50) NULL,
  `Date` DATE NULL,
  `Text` TEXT NULL,
  `Registered_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Report`, `Registered_ID`),
  INDEX `fk_Report_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Report_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Message` (
  `ID_Message` INT NOT NULL AUTO_INCREMENT,
  `Content` TEXT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`ID_Message`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Plataform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Plataform` (
  `ID_Plataform` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(45) NULL,
  PRIMARY KEY (`ID_Plataform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Offer` (
  `ID_Offer` INT NOT NULL AUTO_INCREMENT,
  `Discount` FLOAT NULL,
  PRIMARY KEY (`ID_Offer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Game` (
  `ID_Game` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Price` FLOAT NULL,
  `Stock` INT NULL,
  `Plataform_ID` INT NOT NULL,
  `Offer_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Game`, `Plataform_ID`, `Offer_ID`),
  INDEX `fk_Game_Plataform1_idx` (`Plataform_ID` ASC),
  INDEX `fk_Game_Offer1_idx` (`Offer_ID` ASC),
  CONSTRAINT `fk_Game_Plataform1`
    FOREIGN KEY (`Plataform_ID`)
    REFERENCES `worldgames`.`Plataform` (`ID_Plataform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Offer1`
    FOREIGN KEY (`Offer_ID`)
    REFERENCES `worldgames`.`Offer` (`ID_Offer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Genre` (
  `ID_Genre` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(45) NULL,
  PRIMARY KEY (`ID_Genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Shopping` (
  `ID_Shopping` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `TotalPrice` FLOAT NULL,
  `Tax` FLOAT NULL,
  PRIMARY KEY (`ID_Shopping`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Comment` (
  `ID_Comment` INT NOT NULL AUTO_INCREMENT,
  `Game_ID` INT NOT NULL,
  `Text` TEXT NULL,
  PRIMARY KEY (`ID_Comment`, `Game_ID`),
  INDEX `fk_Comment_Game1_idx` (`Game_ID` ASC),
  CONSTRAINT `fk_Comment_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Valoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Valoration` (
  `ID_Valoration` INT NOT NULL AUTO_INCREMENT,
  `Valoration` CHAR(45) NULL,
  PRIMARY KEY (`ID_Valoration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Complaint` (
  `ID_Complaint` INT NOT NULL AUTO_INCREMENT,
  `Reason` CHAR(45) NULL,
  `Date` DATE NULL,
  `Status` CHAR(45) NULL,
  PRIMARY KEY (`ID_Complaint`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Game_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Game_has_Genre` (
  `Game_ID` INT NOT NULL,
  `Genre_ID` INT NOT NULL,
  PRIMARY KEY (`Game_ID`, `Genre_ID`),
  INDEX `fk_Game_has_Genre_Genre1_idx` (`Genre_ID` ASC),
  INDEX `fk_Game_has_Genre_Game1_idx` (`Game_ID` ASC),
  CONSTRAINT `fk_Game_has_Genre_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Genre_Genre1`
    FOREIGN KEY (`Genre_ID`)
    REFERENCES `worldgames`.`Genre` (`ID_Genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Admistrador_has_Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Admistrador_has_Report` (
  `Report_ID` INT NOT NULL AUTO_INCREMENT,
  `Admistrador_ID` INT NOT NULL,
  `Registered_ID` INT NOT NULL,
  PRIMARY KEY (`Report_ID`, `Admistrador_ID`, `Registered_ID`),
  INDEX `fk_Admistrador_has_Report_Report1_idx` (`Report_ID` ASC),
  INDEX `fk_Admistrador_has_Report_Admistrador1_idx` (`Admistrador_ID` ASC),
  INDEX `fk_Admistrador_has_Report_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Admistrador_has_Report_Admistrador1`
    FOREIGN KEY (`Admistrador_ID`)
    REFERENCES `worldgames`.`Administrator` (`ID_Administrator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admistrador_has_Report_Report1`
    FOREIGN KEY (`Report_ID`)
    REFERENCES `worldgames`.`Report` (`ID_Report`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Admistrador_has_Report_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Professional_has_Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Professional_has_Report` (
  `Professional_ID` INT NOT NULL,
  `Report_ID` INT NOT NULL,
  `Registered_ID` INT NOT NULL,
  PRIMARY KEY (`Professional_ID`, `Report_ID`, `Registered_ID`),
  INDEX `fk_Professional_has_Report_Report1_idx` (`Report_ID` ASC),
  INDEX `fk_Professional_has_Report_Professional1_idx` (`Professional_ID` ASC),
  INDEX `fk_Professional_has_Report_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Professional_has_Report_Professional1`
    FOREIGN KEY (`Professional_ID`)
    REFERENCES `worldgames`.`Professional` (`ID_Professional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professional_has_Report_Report1`
    FOREIGN KEY (`Report_ID`)
    REFERENCES `worldgames`.`Report` (`ID_Report`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professional_has_Report_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Game_has_Shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Game_has_Shopping` (
  `Game_ID` INT NOT NULL,
  `Shopping_ID` INT NOT NULL,
  `Registered_ID` INT NOT NULL,
  PRIMARY KEY (`Game_ID`, `Shopping_ID`, `Registered_ID`),
  INDEX `fk_Game_has_Shopping_Shopping1_idx` (`Shopping_ID` ASC),
  INDEX `fk_Game_has_Shopping_Game1_idx` (`Game_ID` ASC),
  INDEX `fk_Game_has_Shopping_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Game_has_Shopping_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Shopping_Shopping1`
    FOREIGN KEY (`Shopping_ID`)
    REFERENCES `worldgames`.`Shopping` (`ID_Shopping`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Shopping_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Registered_has_Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Registered_has_Comment` (
  `Registered_ID` INT NOT NULL,
  `Comment_ID` INT NOT NULL,
  `Game_ID` INT NOT NULL,
  PRIMARY KEY (`Registered_ID`, `Comment_ID`, `Game_ID`),
  INDEX `fk_Registered_has_Comment_Comment1_idx` (`Comment_ID` ASC),
  INDEX `fk_Registered_has_Comment_Registered1_idx` (`Registered_ID` ASC),
  INDEX `fk_Registered_has_Comment_Game1_idx` (`Game_ID` ASC),
  CONSTRAINT `fk_Registered_has_Comment_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered_has_Comment_Comment1`
    FOREIGN KEY (`Comment_ID`)
    REFERENCES `worldgames`.`Comment` (`ID_Comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered_has_Comment_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Registered_has_Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Registered_has_Game` (
  `Registered_ID` INT NOT NULL,
  `Game_ID` INT NOT NULL,
  PRIMARY KEY (`Registered_ID`, `Game_ID`),
  INDEX `fk_Registered_has_Game_Game1_idx` (`Game_ID` ASC),
  INDEX `fk_Registered_has_Game_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Registered_has_Game_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered_has_Game_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Game_has_Valoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Game_has_Valoration` (
  `Game_ID_Game` INT NOT NULL,
  `Valoration_ID` INT NOT NULL,
  `Registered_ID` INT NOT NULL,
  PRIMARY KEY (`Game_ID_Game`, `Valoration_ID`, `Registered_ID`),
  INDEX `fk_Game_has_Valoration_Valoration1_idx` (`Valoration_ID` ASC),
  INDEX `fk_Game_has_Valoration_Game1_idx` (`Game_ID_Game` ASC),
  INDEX `fk_Game_has_Valoration_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Game_has_Valoration_Game1`
    FOREIGN KEY (`Game_ID_Game`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Valoration_Valoration1`
    FOREIGN KEY (`Valoration_ID`)
    REFERENCES `worldgames`.`Valoration` (`ID_Valoration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Valoration_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Game_has_Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Game_has_Complaint` (
  `Game_ID` INT NOT NULL,
  `Complaint_ID` INT NOT NULL,
  `Professional_ID` INT NOT NULL,
  PRIMARY KEY (`Game_ID`, `Complaint_ID`, `Professional_ID`),
  INDEX `fk_Game_has_Complaint_Complaint1_idx` (`Complaint_ID` ASC),
  INDEX `fk_Game_has_Complaint_Game1_idx` (`Game_ID` ASC),
  INDEX `fk_Game_has_Complaint_Professional1_idx` (`Professional_ID` ASC),
  CONSTRAINT `fk_Game_has_Complaint_Game1`
    FOREIGN KEY (`Game_ID`)
    REFERENCES `worldgames`.`Game` (`ID_Game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Complaint_Complaint1`
    FOREIGN KEY (`Complaint_ID`)
    REFERENCES `worldgames`.`Complaint` (`ID_Complaint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Complaint_Professional1`
    FOREIGN KEY (`Professional_ID`)
    REFERENCES `worldgames`.`Professional` (`ID_Professional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `worldgames`.`Registered_has_Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `worldgames`.`Registered_has_Message` (
  `Registered_ID` INT NOT NULL,
  `Message_ID` INT NOT NULL,
  PRIMARY KEY (`Registered_ID`, `Message_ID`),
  INDEX `fk_Registered_has_Message_Message1_idx` (`Message_ID` ASC),
  INDEX `fk_Registered_has_Message_Registered1_idx` (`Registered_ID` ASC),
  CONSTRAINT `fk_Registered_has_Message_Registered1`
    FOREIGN KEY (`Registered_ID`)
    REFERENCES `worldgames`.`Registered` (`ID_Registered`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered_has_Message_Message1`
    FOREIGN KEY (`Message_ID`)
    REFERENCES `worldgames`.`Message` (`ID_Message`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
