<script type="text/javascript" src="../resources/js/jquery.min.js"></script>
<script type="text/javascript" src="../resources/js/jquery-ui.js"></script>
<script type="text/javascript" src="../resources/js/jquery.validate.min.js"></script>
<script type="text/javascript" src="../resources/js/calendar.js"></script>
<script type="text/javascript" src="../resources/js/bootstrap.min.js"></script>
<script type="text/javascript" src="../resources/js/adminLogin.js"></script>
<script type="text/javascript" src="../resources/js/adminFunctions.js"></script>
<script type="text/javascript" src="../resources/js/statisticsFunctions/canvasjs.min.js"></script>
<script type="text/javascript" src="../resources/js/statisticsFunctions/statistics.js"></script>
